name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      fail-fast: false
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install
        run: npm ci

      - name: Check All
        run: npm run check

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="$tag" \
            --draft \
            dist/main.js manifest.json
